---
name: yaml_check

'on':
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  run_yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install yamllint
        run: sudo apt-get install yamllint
      - name: Display yamllint version
        run: yamllint --version
      - name: run yamllint
        run: yamllint --strict .
...
